name: Build Ubuntu Minimal Image with Packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install QEMU and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            qemu-system-x86 \
            qemu-utils \
            cloud-image-utils \
            wget \
            unzip

      - name: Install Packer manually
        run: |
          PACKER_VERSION="1.10.1"
          wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
          unzip packer_${PACKER_VERSION}_linux_amd64.zip
          sudo install packer /usr/local/bin/
          packer version

      - name: Verify QEMU installation
        run: |
          qemu-system-x86_64 --version
          qemu-img --version

      - name: Run Packer build
        run: |
          packer init .
          packer build ubuntu-minimal.pkr.hcl
