name: Build Ubuntu Minimal Image with Packer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            packer \
            qemu-system-x86 \
            qemu-utils \
            cloud-image-utils
        shell: bash

      - name: Verify QEMU installation
        run: |
          qemu-system-x86_64 --version
          qemu-img --version

      - name: Run Packer build
        run: |
          packer init .
          packer build ubuntu-minimal.pkr.hcl
